// CORDIC_FFT.v

// Generated using ACDS version 23.1 993

`timescale 1 ps / 1 ps
module CORDIC_FFT (
		input  wire        areset, // areset.reset
		input  wire        clk,    //    clk.clk
		output wire [26:0] q,      //      q.q
		output wire [26:0] r,      //      r.r
		input  wire [25:0] x,      //      x.x
		input  wire [25:0] y       //      y.y
	);

	CORDIC_FFT_CORDIC_0 cordic_0 (
		.clk    (clk),    //    clk.clk
		.areset (areset), // areset.reset
		.x      (x),      //      x.x
		.y      (y),      //      y.y
		.q      (q),      //      q.q
		.r      (r)       //      r.r
	);

endmodule
